name: FE CD

on:
  workflow_run:
    workflows: [FE CI]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
     - name: Download artifact
       uses: dawidd6/action-download-artifact@v2
       with:
        workflow: deploy-fe-artifact.yml
        name: fe-artifact
     - name: Deploy to Github pagesuses
       uses: crazy-max/ghaction-github-pages@v3
       with:
        target_branch: gh-pages
        build_dir: .
    env:
        github_token: ${{secrets.GITHUB_TOKEN}}
# 2. Deploy to github pages

# Useful actions
#  dawidd6/action-download-artifact@v2
#  crazy-max/ghaction-github-pages@v3
